simulator.lightbulb.enabled=true
simulator.temperature.enabled=true
simulator.smoke.enabled=true
simulator.energy.enabled=true
simulator.motion.enabled=true
simulator.fridge.enabled=true
simulator.window.enabled=true

simulator.retries=5
simulator.delay=2s
